version: '3'
services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/usr/local/src/app/backend
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - PYTHONUNBUFFERED=1
            - LOG_LEVEL=DEBUG
            - DEV_MODE=1
            - ELASTICSEARCH_HOST=elasticsearch
        # command: ["main:app", "--host", "0.0.0.0", "--reload"]
        # ports:
        #     - 8888:8888
    frontend:
        build: ./frontend
        # We can't mount the entire UI directory, since JavaScript dependencies
        # (`node_modules`) live at that location.
        volumes:
            - ./frontend/src:/usr/local/src/app/frontend/src
            - ./frontend/public:/usr/local/src/app/frontend/public
            - ./frontend/package.json:/usr/local/src/app/frontend/package.json
            - ./frontend/tsconfig.json:/usr/local/src/app/frontend/tsconfig.json
            - ./frontend/yarn.lock:/usr/local/src/app/frontend/yarn.lock
            # We don't want to mount the codegen-generated api directory since it will
            # be generated in Docker, so specify it as a persistent Docker named volume:
            # https://stackoverflow.com/a/38601156
            - docker_openapi:/usr/local/src/app/frontend/src/api
        environment: 
            - ELASTICSEARCH_HOST=elasticsearch
        # ports:
        #     - 3000:3000
        depends_on: 
            - backend
    proxy:
        build: ./proxy
        ports:
            - 8080:80
        depends_on:
            - frontend
            - backend
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        volumes: 
            - ./elasticsearch_data:/usr/share/elasticsearch/data
        environment: 
            - discovery.type=single-node
        ports: 
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
volumes:
    docker_openapi: