version: '3'
services:
    backend-prod:
        build:
            context: ./backend
            dockerfile: Dockerfile-prod
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - PYTHONUNBUFFERED=1
            - LOG_LEVEL=DEBUG
            - DEV_MODE=1
            - ELASTICSEARCH_HOST=elasticsearch
        # command: ["main:app", "--host", "0.0.0.0", "--reload"]
        # ports:
        #     - 8888:8888
    frontend-prod:
        build: 
            context: ./frontend
            dockerfile: Dockerfile-prod
        environment: 
            - ELASTICSEARCH_HOST=elasticsearch
        # ports:
        #     - 3000:3000
        depends_on: 
            - backend-prod
    proxy:
        build: 
            context: ./proxy
            args:
                CONF_FILE: prod.conf
        ports:
            - 8080:80
        depends_on:
            - frontend-prod
            - backend-prod
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        volumes: 
            - ./elasticsearch_data:/usr/share/elasticsearch/data
        environment: 
            - discovery.type=single-node
        ports: 
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
        deploy:
            resources:
                limits:
                    memory: 1G
volumes:
    docker_openapi: